// Starting data for /event-duties. Duty ids match website/data/eventDuties.ts.

// The starting schedule: activities (date YYYY-MM-DD, time HH:MM or '' for
// any time) with their tasks. Copied into DynamoDB once, the first time the
// API runs; after that the team edits it on the page and this is not read.
export const SEED_ACTIVITIES = [
  {
    id: 'e-seed-setup', date: '2026-10-03', time: '15:00', title: 'Venue setup',
    description: 'Stage, LED, flex, photo booth, donation counter, gifts and other distribution items.',
    todos: [
      'Collect the hall keys from RV Teachers College by 2:45 PM',
      'Check power points near the stage and the LED screen',
      'Receive the LED team and show them where the screen goes',
      'Put up the main flex behind the stage',
      'Put up the entrance banner',
      'Stick direction signs: entrance, toilets, lunch, registration',
      'Set chairs on stage for the chief guests and trustees',
      'Place the podium and test that it does not wobble',
      'Set up the photo booth frame and props near the entrance',
      'Set up the donation counter table with a cash box',
      'Place the UPI QR standee on the donation table',
      'Keep the receipt book (with 80G details) and 2 pens at the counter',
      'Receive gifts and distribution items, count them against the list',
      'Lock gifts, kits and mementos in the storeroom',
      'Stick "Reserved" labels on the front rows for guests',
      'Label rows for each children’s group',
      'Take photos of the finished hall and share in the team group',
    ],
  },
  {
    id: 'e-seed-rehearsal', date: '2026-10-03', time: '18:00', title: 'Run-through and sound check',
    description: 'Emcee, stage manager, AV and cultural items walk through the programme.',
    todos: [
      'Play the welcome video once, full length, with sound',
      'Check the video is readable from the last row',
      'Test both cordless mics and the podium mic',
      'Keep spare batteries for the mics',
      'Emcee reads the full script once on stage',
      'Practise calling up one scholarship batch by name',
      'Children rehearse the prayer and cultural items',
      'Agree light cues with the AV person: dim for the video, full for the stage',
      'Walk the guard of honour route with the NCC officer',
      'Confirm everyone’s reporting time for tomorrow',
    ],
  },
  {
    id: 'e-seed-stay', date: '2026-10-03', time: '20:00', title: 'HD Kote group settles at the church, Chandapura',
    description: '60 people stay the night.',
    todos: [
      'Confirm arrival time with the HD Kote group captains',
      'Receive the group at the church and count heads',
      'Show separate sleeping areas for girls and boys',
      'Hand out mats and blankets',
      'Show toilets and drinking water',
      'Serve dinner',
      'Share the night in-charge phone number with the group',
      'Set alarms for the morning',
      'Confirm breakfast time with the cook',
    ],
  },
  {
    id: 'e-seed-stay-leave', date: '2026-10-04', time: '07:30', title: 'HD Kote group leaves Chandapura',
    description: 'Call the arrival desk when 30 minutes away.',
    todos: [
      'Wake everyone by 6:00 AM',
      'Serve breakfast by 6:45 AM',
      'Check the rooms for forgotten bags',
      'Count heads before boarding',
      'Call the arrival desk when 30 minutes away',
    ],
  },
  {
    id: 'e-seed-core', date: '2026-10-04', time: '08:00', title: 'Core team assembles at the venue',
    description: 'Between 8 and 9 AM, in dress code.',
    todos: [
      'Tick the roll call as each core member arrives',
      'Hand out the printed contact sheet',
      'Walk the hall once to check setup from yesterday',
      'Confirm the caterer arrival time',
      'Confirm LED, sound and photographer have reported',
      'Registration desk ready with name tags by 9:00 AM',
    ],
  },
  {
    id: 'e-seed-arrival', date: '2026-10-04', time: '09:15', title: 'Guest arrival, registration, tea',
    description: 'Volunteers at the entrance. Groups arriving from far away eat first.',
    todos: [
      'Two volunteers at the entrance to greet guests',
      'Registration: sign-in sheet and name tags',
      'Hand each guest a programme sheet',
      'Tea and snacks ready by 9:15 AM',
      'Groups who travelled far eat first',
      'Show each group to its labelled row',
      'Keep a lost child point at the registration desk',
    ],
  },
  {
    id: 'e-seed-guard', date: '2026-10-04', time: '09:40', title: 'Chief guests arrive, NCC guard of honour',
    description: '30 NCC cadets at the entrance. Each guest is met by their escort.',
    todos: [
      'NCC cadets in position at the entrance by 9:30 AM',
      'Keep the chief guests’ parking spots free',
      'Escorts wait at the gate from 9:30 AM',
      'Signal the NCC officer as each guest’s car arrives',
      'Walk each guest to the guest lounge',
      'Offer water or tea in the lounge',
      'Tell the emcee when all guests are seated',
    ],
  },
  {
    id: 'e-seed-open', date: '2026-10-04', time: '10:00', title: 'Emcee opens the programme',
    description: 'Short welcome; asks guests to be seated and phones on silent.',
    todos: [
      'Emcee checks the mic before walking on',
      'Ask guests to be seated and phones on silent',
      'Welcome the chief guests by name',
    ],
  },
  {
    id: 'e-seed-prayer', date: '2026-10-04', time: '10:03', title: 'Prayer / Nada Geethe',
    description: 'Sung by children. Audience stands.',
    todos: [
      'Children ready in the wings by 9:55 AM',
      'Keep the prayer audio ready as a backup',
      'Emcee asks the audience to stand',
    ],
  },
  {
    id: 'e-seed-video', date: '2026-10-04', time: '10:08', title: '10-Year Journey welcome video',
    description: 'Chief guests watch from the front row. Dim the lights.',
    todos: [
      'Keep the video open and paused on the laptop',
      'Keep a backup copy on a pen drive',
      'Dim the hall lights on cue',
      'Check the volume in the first 10 seconds',
      'Bring the lights back up when the video ends',
    ],
  },
  {
    id: 'e-seed-lamp', date: '2026-10-04', time: '10:14', title: 'Lamp lighting',
    description: 'Emcee invites the chief guests and dignitaries to the stage. They light the lamp with both trustees.',
    todos: [
      'Buy or bring the brass lamp (kuthu vilakku)',
      'Buy lamp oil (1 litre) and cotton wicks',
      'Keep a candle, matchbox and a lighter as backup',
      'Keep a plate of flowers and a small towel',
      'Place the lamp centre stage on a stand, on a cloth, away from the curtain',
      'Fill oil and set 5 wicks before 9:30 AM',
      'Keep a bucket of water or sand behind the stage',
      'Light the candle when the emcee calls the guests up',
      'Hand the candle to the chief guest',
      'Photographer ready at the side of the stage',
      'After the programme, put the lamp out and store it safely',
    ],
  },
  {
    id: 'e-seed-honour', date: '2026-10-04', time: '10:19', title: 'Welcoming and honouring the chief guests',
    description: 'Shawl, bouquet or memento, by the trustees. Emcee reads a short introduction of each guest.',
    todos: [
      'Shawls, bouquets and mementos in calling order on a side table',
      'One volunteer hands each item to the trustees',
      'Introductions printed for the emcee',
      'Check the spelling of every guest name on the mementos',
    ],
  },
  {
    id: 'e-seed-founder', date: '2026-10-04', time: '10:26', title: "Founder's address, Charulatha M. R.",
    description: '3 to 4 minutes, just before the chief guests speak.',
    todos: [
      'Print the founder’s speech in large font',
      'Keep water at the podium',
      'Timekeeper signals at 3 minutes',
    ],
  },
  {
    id: 'e-seed-guests', date: '2026-10-04', time: '10:30', title: "Chief guests' address",
    description: 'Each guest is told in advance they have about 15 to 20 minutes.',
    todos: [
      'Tell each guest their speaking time in advance',
      'Keep water at the podium',
      'Timekeeper signals at one minute left',
    ],
  },
  {
    id: 'e-seed-teamphoto', date: '2026-10-04', time: '10:50', title: 'Team photo with the chief guests',
    description: 'Whole team on stage in dress code.',
    todos: [
      'Plan the standing order for the team',
      'Team waits at the side of the stage in dress code',
      'Photographer ready with the wide lens',
      'Take 3 shots, then clear the stage quickly',
    ],
  },
  {
    id: 'e-seed-cultural', date: '2026-10-04', time: '10:55', title: "Children's cultural programme",
    description: '2 to 4 short items (song, dance, skit), each under 6 minutes.',
    todos: [
      'Final list of items and the order they go in',
      'Each item under 6 minutes',
      'Music for each item on the laptop and a pen drive',
      'A room for children to change and wait',
      'One volunteer with the children at all times',
    ],
  },
  {
    id: 'e-seed-scholarship', date: '2026-10-04', time: '11:20', title: 'Scholarship and school-kit distribution',
    description: 'By the chief guests and trustees. Children called in batches with names read out. If a chief guest has to leave early, move this and the felicitation up to follow the team photo.',
    todos: [
      'Kits packed one per child with the name on it',
      'Kits sorted by group and calling order',
      'Printed name list for the emcee',
      'Two volunteers hand kits to the guests in order',
      'Call children up in batches of 10',
      'Photographer takes one photo per batch',
      'Tick each child’s name as they receive the kit',
    ],
  },
  {
    id: 'e-seed-felicitation', date: '2026-10-04', time: '11:45', title: 'Felicitation of our pillars',
    description: 'Donors, partners and key volunteers, felicitated by the chief guests with the trustees.',
    todos: [
      'Printed list of pillars to felicitate',
      'Shawls and mementos in the same order as the list',
      'Call each pillar by name',
    ],
  },
  {
    id: 'e-seed-thanks', date: '2026-10-04', time: '12:00', title: 'Vote of thanks, S. M. Manjunatha',
    description: 'About 3 minutes.',
    todos: [
      'Print the vote of thanks in large font',
      'Add any special guest who came on the day',
    ],
  },
  {
    id: 'e-seed-anthem', date: '2026-10-04', time: '12:04', title: 'National Anthem',
    description: 'Audience stands.',
    todos: [
      'Audio ready as a backup',
      'Emcee asks everyone to stand',
    ],
  },
  {
    id: 'e-seed-groupphotos', date: '2026-10-04', time: '12:06', title: 'Group photos',
    description: 'Chief guests, trustees, children, donors.',
    todos: [
      'Chief guests with trustees',
      'Chief guests with all the children',
      'Donors and partners with the chief guests',
      'Whole team photo',
    ],
  },
  {
    id: 'e-seed-lunch', date: '2026-10-04', time: '12:20', title: 'Lunch',
    description: 'Children served first.',
    todos: [
      'Caterer ready by 12:15 PM',
      'Serve children first',
      'Separate table for the chief guests',
      'Drinking water at every table',
      'Two volunteers keep the queue moving',
      'Food for NCC cadets',
    ],
  },
  {
    id: 'e-seed-departures', date: '2026-10-04', time: '13:30', title: 'Groups leave',
    description: 'HD Kote group leaves first, it has the longest trip.',
    todos: [
      'HD Kote group leaves first',
      'Each captain counts heads before the vehicle leaves',
      'Hand each group their leftover kits or gifts',
      'Check the hall for forgotten bags',
      'Each captain messages the team group when home',
    ],
  },
]

// Starting task lists for duties with several steps. Copied into DynamoDB
// once, like the schedule; after that the team edits them on the page.
export const SEED_DUTY_TASKS = {
  'judge-confirm': [
    'Call the judge\'s office to confirm',
    'Get the exact name and designation in writing',
    'Confirm arrival time and car number',
    'Update the flex, emcee script and memento with the name',
  ],
  'guest-brief': [
    'Write the one-page note about the trust',
    'A trustee checks the note',
    'Send it to Divya Prabhu G R J, IAS',
    'Send it to Bheemashankar S Guled, IPS',
    'Send it to the judge once confirmed',
    'Tell each guest they have 15 to 20 minutes to speak',
  ],
  'venue-booking': [
    'Confirm hall access from 3 PM on 3 October',
    'Confirm power backup',
    'Confirm the AC works',
    'Confirm parking for buses and guest cars',
    'Save the venue contact person\'s number',
    'Pay the balance and keep the receipt',
  ],
  'invites-rsvp': [
    'Make the invite list: donors, partners, headmasters, parents',
    'Send the invite on WhatsApp',
    'Call everyone who has not replied',
    'Share the final count with catering by 30 September',
  ],
  headcount: [
    'Numbers from Radhamani (Beluku)',
    'Numbers from Prabhu (Nisarga)',
    'Numbers from Komathi',
    'Numbers from Rufus',
    'Numbers from Rani',
    'Numbers from Suma (pending)',
    'Numbers from Sumesh',
    'Numbers from Mangala Gowri (pending)',
    'Recheck the adults total',
    'Share final numbers with catering and transport',
  ],
  'transport-confirm': [
    'Driver name and phone for each group',
    'Vehicle number for each group',
    'Pickup point and departure time for each group',
    'Share the details with each group captain',
    'Tell drivers where to park at the venue',
  ],
  catering: [
    'Get two quotes',
    'Fix the menu',
    'Give the final plate count',
    'Confirm lunch is ready by 12:15 PM',
    'Confirm tea and snacks at 9:15 AM',
    'Order drinking water',
    'Pay the advance and keep the receipt',
  ],
  printing: [
    'Main flex design approved by a trustee',
    'Entrance banner',
    'Direction signs',
    'Seat labels',
    'Programme sheet',
    'Certificates',
    'Name lists for the emcee',
    'Collect everything by 2 October',
  ],
  mementos: [
    'Final list of names',
    'Order the mementos',
    'Check the spelling of every name',
    'Buy the shawls',
    'Order bouquets for the morning of 4 October',
    'Label each item in calling order',
  ],
  kits: [
    'Final list of children',
    'Buy the kit items',
    'Pack one kit per child',
    'Label each kit with the child\'s name',
    'Sort kits by group and calling order',
    'Take the kits to the venue on 3 October',
  ],
  toppers: [
    'Get topper names from each pillar',
    'Check the spellings',
    'Print the certificates',
    'Buy the medals',
    'Sort in calling order',
  ],
  consent: [
    'Print consent forms',
    'Send forms to each pillar',
    'Collect the signed forms',
    'Give the photographer a list of children without consent',
  ],
  'dress-code': [
    'Decide the dress code',
    'Share it in the team group',
    'Remind everyone the day before',
  ],
  ncc: [
    'Call the NCC officer to confirm 30 cadets',
    'Fix the reporting time',
    'Plan where the cadets stand',
    'Arrange water, snacks and lunch for the cadets',
    'Print a thank-you certificate',
  ],
  'video-ready': [
    'Get the final video file',
    'Copy it to a pen drive',
    'Copy it to the laptop',
    'Test it on the venue projector',
  ],
  'emcee-script': [
    'Write the script',
    'Add the chief guest introductions',
    'Add the felicitation list',
    'Add the scholarship batches with names',
    'Print two copies in large font',
  ],
  budget: [
    'Make the budget sheet',
    'Keep a cash float for the day',
    'Collect every receipt',
  ],
  'contact-sheet': [
    'Collect the phone number of every duty owner',
    'Add drivers, venue, caterer and NCC officer',
    'Add the nearest hospital',
    'Print 10 copies',
  ],
  'photo-booth': [
    'Get the frame and props',
    'Choose a spot away from the entrance',
    'Check the lighting',
    'Test with a phone photo',
  ],
  'donation-setup': [
    'Table and cloth',
    'Receipt book with 80G details',
    'Print the UPI QR standee',
    'Lockable cash box',
    'Two pens',
  ],
  'sound-check': [
    'Test both cordless mics',
    'Test the podium mic',
    'Keep spare batteries',
    'Play the full video once with sound',
  ],
  'stay-bedding': [
    'Count mats and blankets for 60',
    'Set up the girls\' area, with women adults',
    'Set up the boys\' area',
    'Check the toilets are clean',
    'Keep drinking water cans',
  ],
  'stay-food': [
    'Order dinner for 60',
    'Order breakfast for 60',
    'Confirm the serving times',
    'Plates, cups and water',
  ],
  'first-aid': [
    'Pack the first aid kit',
    'ORS packets',
    'Basic medicines',
    'Note the route to the nearest hospital',
    'One car and driver on standby',
  ],
  'donation-counter': [
    'Two people at the counter at all times',
    'A receipt for every donation',
    'Count the cash with two people at close',
    'Hand cash and receipts to a trustee',
  ],
  registration: [
    'Sign-in sheet',
    'Name tags and markers',
    'Programme sheets',
    'Lost and found box',
  ],
  water: [
    'Order water cans',
    'Place water in the hall and near the stage',
    'Paper cups',
    'Refill every hour',
  ],
  'child-safety': [
    'Brief the volunteers',
    'Women volunteers for girls',
    'Lost child point at registration',
    'Headcount after lunch',
  ],
  'guest-lounge': [
    'Book a quiet room',
    'Water, tea and snacks',
    'Washroom nearby',
    'Chairs for 6',
  ],
  'guard-of-honour': [
    'Brief the NCC cadets on the order of guests',
    'Mark where the cadets stand',
    'Cue plan for each guest',
  ],
  av: [
    'Laptop with the video',
    'Pen drive backup',
    'Mic batteries',
    'List of light cues',
  ],
  'photo-video': [
    'Make a shot list',
    'Charge all batteries',
    'Spare memory cards',
    'Know which children have no photo consent',
  ],
  'social-media': [
    'Plan the posts',
    'Only children with photo consent',
    'Post by the evening',
  ],
  'pack-up': [
    'Count leftover kits and gifts',
    'Return the LED screen',
    'Take down the flex',
    'Return the chairs',
  ],
  accounts: [
    'Total the donations',
    'Pay pending bills',
    'File all receipts',
  ],
  'thank-you': [
    'Thank the chief guests',
    'Thank the NCC officer and cadets',
    'Thank the venue',
    'Thank the caterer',
    'Thank donors and partners',
  ],
  'photos-collect': [
    'Create one shared folder',
    'Collect from the photographer',
    'Collect from the team\'s phones',
  ],
}

// Tasks added after the first release. Each batch is copied in once, into
// new and existing databases alike, under its own key; its ids start with
// its prefix, so batch tasks sort after the starting ones and before any the
// team adds. Add a new batch (new key, next prefix) rather than editing one
// that has already gone live.
export const SEED_TASK_BATCHES = [
  {
    key: 'tasks_2026_09_28_cg_table_donations',
    prefix: '0e',
    tasks: {
      'cg-table': [
        'Name plate: Divya Prabhu G R J, IAS',
        'Name plate: Bheemashankar S Guled, IPS',
        'Name plate: the sitting judge (once confirmed)',
        'Name plates: Charulatha M. R. and S. M. Manjunatha',
        'Check the spelling and designation on every name plate',
        'Tablecloth and skirting in the trust\'s colours',
        'One low flower arrangement that does not block faces or mics',
        'A glass, coaster and a jug of water for each seat',
        'Printed programme with speaking times at each seat',
        'Notepad and pen at each seat',
        'Tissues on the table',
        'One-page note about the trust for each chief guest',
        'A copy of the 10-year magazine for each chief guest',
        'Table mic, if guests will not speak from the podium',
        'Keep mementos, shawls and bouquets on the side table, not here',
        'Table set by 9:30 AM on 4 October',
        'Refill water and clear the table during the programme',
      ],
      'donation-setup': [
        'Standee: "Support the next 10 years", with what a donation does (use the trust\'s real figures)',
        'Display the trust\'s registration, PAN and 12A/80G numbers',
        'Card with bank transfer details, and cheque instructions ("Payable to Law Park Educational Trust")',
        'Envelopes for cheques',
        'Donor register: name, phone, email, amount, mode, PAN (for the 80G certificate), kept in a closed folder',
        'Pledge cards for giving later or every year',
        'Calculator, pen stand and small change',
        'Magazine copies or brochures to hand out',
        'QR code to the trust\'s website',
        '"Thank you" sign',
      ],
      'donation-counter': [
        'Keep the trust\'s phone at the counter with UPI alerts on',
        'Confirm each payment on the phone before writing the receipt',
        'Note the PAN of donors who want an 80G certificate',
        'Closing tally sheet signed by two people',
      ],
    },
  },
]
